services:
  auto-server-backup:
    tty: true
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
      # start the backup right after launching the service
      BACKUP_ON_START: true
      # Where to upload the local files to. The remote name followed by the path on this remote.
      REMOTE_EXPORT_PATH: "onedrive_crypt:pi_backup"
      # When to backup the local files. Can contain multiple timepoint seperated by a single space.
      UPLOAD_SCHEDULE: "17:34:59"
    image: therealjohannes/server_backup
    volumes:
      # mount your local data folders below that you want to be backed up
      # these should be under "/backup/data"
      - ./data:/backup/data:ro

      # the default location of the rclone config (check with `rclone config file`)
      - $HOME/.config/rclone:/root/.config/rclone

      # optional to access the logs
      - ./logs:/backup/logs
